/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jrO22jQmrNQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"; // This marks the component as a Client Component

import React, { useState } from 'react';
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"

export function Component() {
  const [message, setMessage] = useState('');
  const handleSubmit = (event) => {
    event.preventDefault();
    const message = event.target.elements.message.value;
    // Add your logic to send the message to the debate engine
    console.log(message);
  };
  return (
    (<div className="flex flex-col h-screen bg-gray-100 dark:bg-gray-900">
      <header
        className="flex items-center justify-between px-4 py-2 bg-white shadow dark:bg-gray-800">
        <h1 className="text-xl font-bold">Debate Engine</h1>
        <div className="flex items-center space-x-2">
          <Button variant="outline" size="sm">
            Settings
          </Button>
        </div>
      </header>
      <main className="flex-1 p-4 overflow-auto h-full">
        <div
          className="grid grid-cols-1 md:grid-cols-[1fr_300px] gap-4 h-full mx-auto">
          <div
            className="bg-white rounded-lg shadow dark:bg-gray-800 grid grid-cols-2 gap-4 h-full mx-auto">
            <div className="p-4 border-r dark:border-gray-700 h-full">
              <div className="flex items-center justify-between mb-2">
                <h2 className="text-lg font-semibold flex items-center">
                  You
                  <Button variant="ghost" size="icon" className="ml-2">
                    <MicIcon className="w-4 h-4" />
                    <span className="sr-only">Voice Input</span>
                  </Button>
                </h2>
              </div>
              <div className="prose prose-sm max-h-96 overflow-auto dark:prose-invert h-full">
                <form onSubmit={handleSubmit}>
                  <Textarea
                    name="message"
                    placeholder="Type your message..."
                    value={message}
                    onChange={(e) => setMessage(e.target.value)}
                  />
                  <div className="flex justify-end mt-2">
                    <Button variant="outline" type="submit" className="mt-2">
                      Submit
                    </Button>
                  </div>
                </form>
              </div>
            </div>
            <div className="p-4 h-full">
              <div className="flex items-center justify-between mb-2">
                <h2 className="text-lg font-semibold">Debate Engine</h2>
                <Button variant="ghost" size="icon">
                  <VolumeIcon className="w-4 h-4" />
                  <span className="sr-only">Mute</span>
                </Button>
              </div>
              <div
                className="prose prose-sm max-h-96 overflow-auto dark:prose-invert h-full">
                <p>
                  Certainly, climate change is a critical issue that affects all of us. I'm happy to engage in a
                  constructive debate on this topic.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>)
  );
}

function MicIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>)
  );
}

function handleSubmit(event) {
  event.preventDefault();
  const message = event.target.elements.message.value;
  // Add your logic to send the message to the debate engine
  console.log(message);
}

function VolumeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
    </svg>)
  );
}
